### ISSUE TITLE
Port to linux and mac (and also windows 32 bit!)

### ISSUE THREAD

**Issue by jason0597** [knight-ryu12/Seedplanter#9]
The currently bundled ctr-dsiwaretool binary only works for windows 64 bit
It should be 32 bit for maximum compatibility for all windows computers.

Also, ctr-dsiwaretool needs to be recompiled for linux and mac.

Once that is done, then this application will be truly cross-platform thanks to the magic of the JVM

**Comment by knight-ryu12** [comment]
Hence we can head to not use Process invocation by rewritting ~~shitty~~*cough*ctr-dsiwaretool

**Comment by knight-ryu12** [comment]
as well in #5
